# Generated by Django 5.2 on 2025-05-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='calories_burned',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
