# Generated by Django 5.2 on 2025-05-05 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_alter_predictionresult_predicted_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionresult',
            name='predicted_calories',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='workout',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictionresult', to='fitness.workout'),
        ),
    ]
